# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Site title"
description: "A site description"
lang: "en" # or fr, de, es etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Include styles inline or link to css file?
# This has to be set to css: inline for the theme to inline styles
# Set it to anything else, or remove it, to link to /css/style.class

css: inline


# Build settings
markdown: kramdown

sass:
  style: compressed


# Defaults

# Enable is_homepost test for posts
# Enable is_page test for pages
# Enable is_home test for home page
# Use {% if page.is_post %} etc.

defaults:
-
    scope:
        path: "/"      # empty string for all files
    values:
        is_home: true
-
    scope:
        path: ""
        type: posts
    values:
        is_post: true
-
    scope:
        path: ""
        type: pages
    values:
        is_page: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
