lang: "en"
title: "Leon Paternoster"
author: "Leon Paternoster" # for blog post attribution
description: "Head of digital and marketing at Suffolk Libraries. Developer of library self-service systems and simple, fast and friendly websites."
email: leon.paternoster@zoho.com
linkedin: https://uk.linkedin.com/in/leonpaternoster
twitter: https://mobile.twitter.com/leonpaternoster
github: https://github.com/leonp/
microblog: https://micro.blog/leonp/
webmention-pingback: https://webmention.io/www.leonpaternoster.com/xmlrpc
webmention-mention: https://webmention.io/www.leonpaternoster.com/webmention
me: https://micro.blog/leonp/

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.leonpaternoster.com" # the base hostname & protocol for your site

# hide-skip-link: true

# Build settings
permalink: /posts/:title/

# Time
timezone: Europe/London


# Include styles inline or link to css file?
# This has to be set to css: inline for the theme to inline styles
# Set it to anything else, or remove it, to link to /css/style.class
css: external


# Build settings
markdown: kramdown
sass:
  style: compressed


# Defaults

# Enable is_homepost test for posts
# Enable is_page test for pages
# Enable is_home test for home page
# Use {% if page.is_post %} etc.

defaults:
-
    scope:
        path: "/"      # empty string for all files
    values:
        is_home: true
-
    scope:
        path: ""
        type: posts
    values:
        is_post: true
        layout: post
-
    scope:
        path: ""
        type: pages
    values:
        is_page: true


# webmentions

# webmentions:
  # username: www.leonpaternoster.com
  # cache_folder: _data/webmentions
  # legacy_domains:
    # - http://leonpaternoster.com
    # - http://www.leonpaternoster.com


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

# This is a Netlify file, feel free to delete unless you need it
include: [_redirects]
